:tada: v0.4.0
GraiaCommunity/graiax-fastapi pull request #2
Opened 2023-08-08 15:05 UTC by Redlnn

- 抛弃旧版 Launart（`<0.7.0`）、Amnesia（`<0.8.0`）支持
- 支持新版 Launart（`>=0.7.0`）及 Amnesia（`>=0.8.0`）
- 由于 Launart 拦截了 Service 中的异常，coverage 并不能捕获，测试将会永远 100% PASSED

2023-08-08 15:08 UTC, GreyElaina commented on README.md
这里我建议提及 Ariadne 的不兼容告示

2023-08-08 15:18 UTC, GreyElaina commented on README.md
> +avilla = Avilla(broadcast=broadcast, launch_manager=launart, message_cache_size=0)
launart 0.8.0 开始支持 creart, 建议使用 creart，只是 avilla 并没有在 1.0.0a6 用上

2023-08-08 15:20 UTC, GreyElaina commented on README.md
> +launart.add_component(UvicornASGIService("127.0.0.1", 9000, {"": fastapi}))  # type:ignore
这个倒很奇怪的……我建议你写点注释，像你这样 ob11 的 ws server 就可能寄了。
虽然更新一下 amnesia，改写成深度优先就好了

2023-08-08 15:20 UTC, GreyElaina commented on README.md
> +launart.add_component(UvicornASGIService("127.0.0.1", 9000, {"": fastapi}))  # type:ignore
哦你下面写了

2023-08-08 15:21 UTC, GreyElaina commented on README.md
>  @listen(ApplicationLaunched)
……欸，Avilla 是 `ApplicationPreparing` 来着？

2023-08-08 15:22 UTC, GreyElaina commented on pyproject.toml
> +    "uvicorn[standard]>=0.23.2",
这个不应该由你来依赖吧

2023-08-08 15:22 UTC, Redlnn commented on README.md
>  @listen(ApplicationLaunched)
啊，忘记改惹

2023-08-08 15:23 UTC, Redlnn commented on pyproject.toml
> +    "uvicorn[standard]>=0.23.2",
也行，那得对 websockets 包是否存在做特判了

2023-08-08 15:24 UTC, GreyElaina commented on src/graiax/fastapi/interface.py
> +    else:
额……为什么不直接 add_api_route = FastAPI.add_api_route 呢

2023-08-08 15:26 UTC, GreyElaina requested changes
有一些问题……

2023-08-08 15:27 UTC, Redlnn commented on src/graiax/fastapi/interface.py
> +    else:
草，好像很有道理，为什么呢🤤

2023-08-09 12:42 UTC, Redlnn commented on pyproject.toml
> +    "uvicorn[standard]>=0.23.2",
最后选择不特判了~

2023-08-09 13:45 UTC, GreyElaina approved these changes

2023-08-10 12:13 UTC, merged